name: Auto-claim issues from PR

on:
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: read

jobs:
  claim-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on linked issues
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const prNumber = context.payload.pull_request.number;
            const user = context.payload.pull_request.user.login;
            const prUrl = context.payload.pull_request.html_url;

            const issueNumbers = new Set();
            const pattern = /(?:closes|fixes|resolves)\s+#(\d+)/gi;

            const prBody = context.payload.pull_request.body;
            if (prBody) {
              for (const match of prBody.matchAll(pattern)) {
                issueNumbers.add(match[1]);
              }
            }

            const { data: commits } = await github.rest.pulls.listCommits({
              owner: owner,
              repo: repo,
              pull_number: prNumber,
            });

            for (const commit of commits) {
              const commitMessage = commit.commit.message;
              if (commitMessage) {
                for (const match of commitMessage.matchAll(pattern)) {
                  issueNumbers.add(match[1]);
                }
              }
            }
            
            if (issueNumbers.size === 0) {
              console.log('No linked issues found in PR body or commit messages.');
              return;
            }

            const commentBody = `**Issue claimed!**\n\nContributor @${user} has opened a pull request that addresses this issue: ${prUrl}\n\nTo avoid duplicate work, please check the PR before starting.`;

            for (const issueNumber of issueNumbers) {
              console.log(`Adding comment to issue #${issueNumber}`);
              try {
                await github.rest.issues.createComment({
                  owner: owner,
                  repo: repo,
                  issue_number: issueNumber,
                  body: commentBody,
                });
                console.log(`Successfully commented on issue #${issueNumber}`);
              } catch (error) {
                console.log(`Failed to comment on issue #${issueNumber}: ${error.message}`);
              }
            }