name: Auto-assign or comment on issues

on:
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: read

jobs:
  assign-or-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Attempt to assign issue, comment on failure
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const prNumber = context.payload.pull_request.number;
            const assignee = context.payload.pull_request.user.login;
            const prUrl = context.payload.pull_request.html_url;

            const issueNumbers = new Set();
            const pattern = /(?:closes|fixes|resolves)\s+#(\d+)/gi;

            const prBody = context.payload.pull_request.body;
            if (prBody) {
              for (const match of prBody.matchAll(pattern)) {
                issueNumbers.add(match[1]);
              }
            }

            const { data: commits } = await github.rest.pulls.listCommits({
              owner: owner,
              repo: repo,
              pull_number: prNumber,
            });

            for (const commit of commits) {
              const commitMessage = commit.commit.message;
              if (commitMessage) {
                for (const match of commitMessage.matchAll(pattern)) {
                  issueNumbers.add(match[1]);
                }
              }
            }
            
            if (issueNumbers.size === 0) {
              console.log('No linked issues found.');
              return;
            }

            for (const issueNumber of issueNumbers) {
              try {
                console.log(`Attempting to assign issue #${issueNumber} to @${assignee}`);
                await github.rest.issues.addAssignees({
                  owner: owner,
                  repo: repo,
                  issue_number: issueNumber,
                  assignees: [assignee],
                });
                console.log(`Successfully assigned issue #${issueNumber} to @${assignee}`);

              } catch (error) {
                console.log(`Could not assign issue #${issueNumber}. Defaulting to a comment. Error: ${error.message}`);
                
                const commentBody = `**Issue claimed!**\n\nContributor @${assignee} has opened a pull request that addresses this issue: ${prUrl}\n\nThis issue could not be assigned automatically. To avoid duplicate work, please check the PR before starting.`;
                
                await github.rest.issues.createComment({
                  owner: owner,
                  repo: repo,
                  issue_number: issueNumber,
                  body: commentBody,
                });
                console.log(`Successfully commented on issue #${issueNumber} as a fallback.`);
              }
            }